  @bot.message_handler(commands=['go', 'start'])  
def welcome(message):
    sti = open(path+'stiker.tgs', 'rb')
    bot.send_sticker(message.chat.id, sti)
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)

    ititem4 = types.KeyboardButton("РУТОР")
    ititem3 = types.KeyboardButton("ПРАЙС")
    item2 = types.KeyboardButton("ЛОКАЦИЯ")
    item1 = types.KeyboardButton('ТЕХ,ПОДДЕРЖКА')

    markup.add(item1, item2, item3)

    bot.send_message(message.chat.id,
                     "Добро пожаловать, {0.first_name}!\\n\\nЯ - <b>{1.first_name}</b>, вашему вниманию хотим предоставить магазин ПАВ веществ Rick and Morti, "
                     "здесь вы можете приобрести товар какой  по душе, "
                     "чтобы перейти к каттологу нашего магазина нажмите инетересующее вам меню,"
                     "так же переходите на РУТОР там вы можете ознакомится с нами по ближе и посмотреть отзывы клиентов.\\n\\n"
                     "<i>Have a nice time</i>".format(
                         message.from_user, bot.get_me()),
                     parse_mode='html', reply_markup=markup)          
  
